#Comando pra deixar o console mais clean
logging:
  pattern:
    console: "%d{yyyy-MM HH:mm} == %logger{2} >>> %msg%n"

#Comando pra deixar a tela 404 mais limpa
server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  #Config pra toda vez que iniciar o banco ele vai atualizar o banco
  jpa:
    hibernate:
      ddl-auto: update